import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — Poppys",
  description:
    "Poppy runs entirely on your device. We do not collect, transmit, sell, or share your personal data.",
};

const H2 =
  "mt-[36px] mb-[12px] font-display text-[clamp(1.5rem,3vw,2.1rem)] font-normal leading-[1.1] text-[color:var(--leaf)]";
const P =
  "my-[12px] text-[1rem] leading-[1.7] text-[color:rgba(7,18,7,0.82)]";
const LI = "leading-[1.7] text-[color:rgba(7,18,7,0.82)]";

export default function Privacy() {
  return (
    <main className="h-screen overflow-y-auto bg-[var(--sky-soft)] px-[20px] py-[48px] text-[color:var(--leaf)]">
      <article className="mx-auto w-[min(760px,100%)] rounded-[14px] border border-[color:var(--line)] bg-[var(--panel)] px-[clamp(20px,5vw,52px)] py-[clamp(28px,5vw,48px)] shadow-[0_24px_80px_rgba(7,18,7,0.12)] backdrop-blur-[14px]">
        <Link
          href="/"
          className="inline-block font-mono text-[0.8rem] font-extrabold uppercase text-[color:var(--poppy)] hover:underline"
        >
          Poppys
        </Link>

        <h1 className="mt-[10px] font-display text-[clamp(2.4rem,6vw,3.6rem)] font-normal leading-[1] text-[color:var(--leaf)]">
          Privacy Policy
        </h1>
        <p className="mt-[8px] font-mono text-[0.82rem] font-bold uppercase tracking-wide text-[color:rgba(7,18,7,0.55)]">
          Effective date: August 1, 2026
        </p>

        <p className={`${P} mt-[24px]`}>
          Poppy (&ldquo;Poppy&rdquo;, &ldquo;the app&rdquo;, &ldquo;we&rdquo;,
          &ldquo;us&rdquo;) is a personal AI voice companion. This policy explains what the
          app does with your information. The short version:{" "}
          <strong>
            Poppy runs entirely on your device. We do not collect, transmit, sell, or share
            your personal data.
          </strong>{" "}
          There are no accounts, no cloud servers, and no third-party AI services.
        </p>
        <p className={P}>
          If anything here is unclear, contact us at{" "}
          <strong>poppysdotsocial@gmail.com</strong>.
        </p>

        <h2 className={H2}>The one-line summary</h2>
        <p className={P}>
          Everything you say to Poppy, everything she remembers, and every conversation
          stays on your own device. It never leaves your machine, and we never see it.
        </p>

        <h2 className={H2}>What Poppy processes, and where</h2>
        <p className={P}>
          All of the following happens locally on your device. None of it is sent to us or
          to any third party.
        </p>
        <ul className="my-[12px] grid list-disc gap-[10px] pl-[22px] text-[1rem]">
          <li className={LI}>
            <strong>Your voice (microphone).</strong> When you are on a call, Poppy uses
            your microphone to hear you. The audio is converted to text on your device and
            is not recorded, stored, or uploaded. It is discarded after it is transcribed.
          </li>
          <li className={LI}>
            <strong>Your messages and Poppy&rsquo;s replies.</strong> The conversation is
            generated by an AI model that runs on your device. Nothing is sent to an
            external server to produce a reply.
          </li>
          <li className={LI}>
            <strong>Poppy&rsquo;s voice.</strong> Her spoken replies are synthesized on your
            device.
          </li>
          <li className={LI}>
            <strong>Conversation history.</strong> Your chats are stored locally on your
            device so the app works and you can review them. They are not uploaded.
          </li>
          <li className={LI}>
            <strong>Memory.</strong> With your explicit consent, Poppy remembers facts you
            choose to save. These memories are stored locally and encrypted on your device.
            Each character keeps its own separate memory. You can view, edit, or delete any
            memory, or clear all of them, at any time in the app.
          </li>
        </ul>

        <h2 className={H2}>What we do NOT do</h2>
        <ul className="my-[12px] grid list-disc gap-[8px] pl-[22px] text-[1rem]">
          {[
            "We do not collect or receive any of your data.",
            "We do not transmit your voice, conversations, or memories off your device.",
            "We do not use accounts or logins.",
            "We do not use third-party AI services or share data with them.",
            "We do not use advertising, third-party analytics, or cross-app tracking.",
            "We do not sell or rent your information to anyone.",
          ].map((t) => (
            <li key={t} className={LI}>
              {t}
            </li>
          ))}
        </ul>

        <h2 className={H2}>App analytics</h2>
        <p className={P}>
          Poppy may keep simple, content-free usage counts on your device (for example,
          &ldquo;a call happened&rdquo;) to power in-app features like your streak. These
          counts contain no conversation content and no personal information, and they are
          not transmitted off your device.
        </p>

        <h2 className={H2}>Permissions the app asks for</h2>
        <ul className="my-[12px] grid list-disc gap-[8px] pl-[22px] text-[1rem]">
          <li className={LI}>
            <strong>Microphone.</strong> Used only during a call, only to hear you, and only
            on your device, as described above. You can revoke this permission in your system
            settings at any time.
          </li>
          <li className={LI}>
            <strong>Notifications (optional).</strong> If you opt into a daily ritual
            reminder, the app schedules a local notification on your device. No notification
            data leaves your device.
          </li>
        </ul>

        <h2 className={H2}>Your control over your data</h2>
        <p className={P}>
          Because your data lives only on your device, you are always in control:
        </p>
        <ul className="my-[12px] grid list-disc gap-[8px] pl-[22px] text-[1rem]">
          {[
            "Review everything Poppy remembers in the app.",
            "Edit or delete any individual memory.",
            "Clear all memories or your conversation history at any time.",
            "Delete everything by removing the app; this deletes all local Poppy data on that device.",
          ].map((t) => (
            <li key={t} className={LI}>
              {t}
            </li>
          ))}
        </ul>

        <h2 className={H2}>Security</h2>
        <p className={P}>
          Saved memories are encrypted at rest on your device with industry-standard
          encryption, and the encryption key is stored locally and readable only by your
          user account. This is privacy hygiene for an on-device app. As with any software,
          please keep your device and operating system secure and up to date.
        </p>

        <h2 className={H2}>Children</h2>
        <p className={P}>
          Poppy is not directed to children. Please do not use the app if you are under the
          age required by the app&rsquo;s App Store age rating in your region.
        </p>

        <h2 className={H2}>Changes to this policy</h2>
        <p className={P}>
          If we change how the app handles your information, we will update this policy and
          change the effective date above. If a future version of the app ever adds an
          optional feature that sends any data off your device, we will disclose it clearly
          and ask for your consent before it is used.
        </p>

        <h2 className={H2}>Contact</h2>
        <p className={P}>
          Questions about privacy? Email us at <strong>poppysdotsocial@gmail.com</strong>.
        </p>

        <div className="mt-[40px] border-t border-[color:var(--line)] pt-[20px]">
          <Link
            href="/"
            className="font-mono text-[0.82rem] font-extrabold uppercase text-[color:var(--poppy)] hover:underline"
          >
            &larr; Back to Poppys
          </Link>
        </div>
      </article>
    </main>
  );
}
